### ISSUE TITLE
After update firmware V1_1.bin my bluetooth died

### ISSUE THREAD

**Issue by iFernandoSousa** [bjoerke/HM-10-Firmware#1]
I trying to Update my HM-10 Copy, and try install this version V1_1.bin but after install, my bluetooth blink the RED light for 3 times and died, do not blink more and do not allowed to discover on mobile.

I try back the HM-10 firmware but received the message bellow:

C:\ccloader>CCLoader.exe 3 CC2541hm10v540.bin 0
Copyright (c) 2013 RedBearLab.com
CCLoader.exe version 0.5
Comport : COM3
Bin file: CC2541hm10v540.bin
Device  : Default (e.g. UNO)

Comport open!
<Baud:115200> <data:8> <parity:none> <stopbit:1> <DTR:off> <RTS:off>

File open!
Block total: 512

Enable transmission...
Request sent already!
/********************************************************************/
* If there is no respond last for 3s, please press "Ctrl+C" to exit!
* And pay attention to :
*   1. The connection between computer and Arduino;
*   2. The connection between Arduino and CC2540;
*   3. Whether the device you using is Leonardo or not;
*   4. Other unexpected errors.
/********************************************************************/

Waiting for respond from Arduino...

No chip detected!
Upload Failed!
File closed!
Comport closed!

---------
Have some way to survive this bluetooth again without Serial Adapter?
Have another firmware that work without 32Clock external cristal (Copy version of HM-10)?

**Comment by vprithiviraj** [comment]
oh then it has gone. plan for new module.
